name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
api-version: 1.17
author: ${author}

commands:
    vehicle:
        description: Main plugin command
        usage: /<command> [args]
        aliases: [craft]
permissions: