name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
api-version: 1.17
author: ${author}

commands:
    vehicle:
        description: Contains administrative-type commands that involve the plugin operation as a whole
        usage: /<command> [args]
        aliases: [craft]
    craft:
        description: Contains user-type commands that involve a specific craft that the player is attached to 
permissions:
    vehicles.admin:
        description: Base admin command, allows access to /vehicle
        default: op
    vehicles.user:
        description: Base user command, allows access to /craft
        default: true